import Navbar from '@/components/Navbar'
import DotPattern from '@/components/ui/dot-pattern'
import { cn } from '@/lib/utils'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Contact | Aditya Portfolio',
  description: 'Generated by create next app',
}

export default function ContactLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="overflow-auto">
      <DotPattern
        cr={1}
        className={cn('[mask-image:radial-gradient(400px_circle_at_center,white,transparent)]')}
      />
      <Navbar />
      {children}
    </div>
  )
}
