import Navbar from '@/components/Navbar'
import { BackgroundLines } from '@/components/ui/background-lines'

import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About | Aditya Portfolio',
  description: 'Generated by create next app',
}

export default function AboutLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <BackgroundLines className="h-screen w-full">
      <Navbar />
      {children}
    </BackgroundLines>
  )
}
