import Navbar from '@/components/Navbar'
import { BackgroundBeamsWithCollision } from '@/components/ui/background-beams-with-collision'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About | Aditya Portfolio',
  description: 'Generated by create next app',
}

export default function AboutLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <BackgroundBeamsWithCollision className="overflow-auto">
      <Navbar />
      {children}
    </BackgroundBeamsWithCollision>
  )
}
