// app/(home)/layout.tsx
import Navbar from '@/components/Navbar'
import { BackgroundBeamsWithCollision } from '@/components/ui/background-beams-with-collision'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home | Aditya Portfolio',
  description: 'Generated by create next app',
}

export default function HomeLayout({ children }: { children: React.ReactNode }) {
  return (
    <BackgroundBeamsWithCollision className="overflow-hidden">
      <Navbar />
      {children}
    </BackgroundBeamsWithCollision>
  )
}
